import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]


[font]
normal = { family = "0xProto Nerd Font Mono" }
bold = { family = "0xProto Nerd Font Mono" }
italic = { family = "0xProto Nerd Font Mono" }
